= Emerald Legacy Story Archive

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/emerald-legacy/story-archive/workflows/Story%20releases/badge.svg?branch=main["Stories"]
image:https://img.shields.io/github/last-commit/emerald-legacy/story-archive/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/emerald-legacy/story-archive.svg["Contributors",link="https://github.com/emerald-legacy/story-archive/graphs/contributors"]
image:https://img.shields.io/github/issues/emerald-legacy/story-archive.svg["Issues",link="https://github.com/emerald-legacy/story-archive/issues"]
image:https://img.shields.io/github/issues-closed/emerald-legacy/story-archive.svg["Issues closed",link="https://github.com/emerald-legacy/story-archive/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


== Content
This repository contains all stories by Emerald Legacy in asciidoc. They are published to GitHub pages as rendered PDF files.

toc::[]

== How to contribute or participate
If you find a typo, bad formatting, or anything else you think we should improve, please create an issue or a pull-request!

== How to translate a story
Choose a story in our Google Drive, copy the text to a new asciidoc file, and apply asciidoc formatting. You can check the existing stories as orientation for text formatting, title/background formatting, and image inclusion.

== How to build the documents

Prerequisite: You need a Java Runtime(tm) installed.

You build the output documents with gradle. That will produce both pdf and html.

`./gradlew renderStories`

== Maintainers

This repository is currently maintained by Ben Wolf (Hida Amoro, programming-wolf).
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.
